# Generated by Django 5.2.8 on 2026-02-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_coupon_cart_invoice_newslettersubscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.AddField(
            model_name='invoice',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='myapp.cartorder'),
        ),
    ]
