# Generated by Django 5.2.8 on 2026-02-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_invoice_order_invoice_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
