# Generated by Django 5.2.8 on 2026-02-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cartorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay'), ('upi_qr', 'UPI QR / Manual Transfer')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='UTR or transaction ID from payment', max_length=100, null=True),
        ),
    ]
